title: Page

pages:
  template: default
  num: zero

files:
  fields: 
    alt: imagefields
  
fields:
  title:
    label: Title
    type: title
    
  text:
    label: Text
    type: markdown
    
  coverimage: coverimage