title: Site

fields:
  title:
    label: Title
    type:  text

  description:
    label: Description
    type:  textarea
    buttons:
    help: This is the website description that also shows up under the search result in Google

  footer_menu:
    label: Footer menu
    type: structure
    style: table
    translate: false
    fields:
      page:
        label: Page
        type: select
        options: pages

  maintenance_mode:
    label: Maintenance mode
    type: toggle
    translate: false
    width: 1/2
    default: no
    help: If you turn this option on, the site will be put in maintenance mode and redirect anyone that is not logged in to the 'Coming Soon' page
